#!/bin/bash
set -eu -o pipefail

OUTPUT_FILE=/opt/quorum/bin/run-init-quorum

VAULT_DNS=$1
VAULT_PORT=$2

VAULT_URL="https://$VAULT_DNS:$VAULT_PORT"

# Write the run-init-quorum script
cat << EOF_OUTER > $OUTPUT_FILE
#!/bin/bash
set -eu -o pipefail

SUPERVISOR_CONFIG="/etc/supervisor/conf.d/init-quorum-supervisor.conf"

# Write the init-quorum supervisor config
cat << EOF > \$SUPERVISOR_CONFIG
[program:init-quorum]
command=/opt/quorum/bin/init-quorum.sh
stdout_logfile=/opt/quorum/log/init-quorum-stdout.log
stderr_logfile=/opt/quorum/log/init-quorum-error.log
numprocs=1
autostart=true
autorestart=unexpected
stopsignal=INT
user=ubuntu
environment=VAULT_ADDR=$VAULT_URL
EOF

# Read and run the supervisor config
sudo supervisorctl reread
sudo supervisorctl update
EOF_OUTER

# Give permission to run the script
sudo chown ubuntu $OUTPUT_FILE
sudo chmod 744 $OUTPUT_FILE
