#!/bin/bash
set -eu -o pipefail

SUPERVISOR_CONFIG="/etc/supervisor/conf.d/init-quorum-supervisor.conf"

# Write the init-quorum supervisor config
cat << EOF > $SUPERVISOR_CONFIG
[program:init-bootnode]
command=/opt/quorum/bin/init-bootnode.sh
stdout_logfile=/opt/quorum/log/init-bootnode-stdout.log
stderr_logfile=/opt/quorum/log/init-bootnode-error.log
numprocs=1
autostart=true
autorestart=unexpected
stopsignal=INT
user=ubuntu
environment=VAULT_ADDR=https://vault.service.consul:8200
EOF

# Read and run the supervisor config
sudo supervisorctl reread
sudo supervisorctl update
