public_key_path = "~/.ssh/quorum.pub"
private_key_path = "~/.ssh/quorum"
key_name = "quorum-cluster"
aws_region = "us-east-1"
quorum_azs = ["us-east-1a", "us-east-1b", "us-east-1c"]
vault_cluster_size = 1
vault_instance_type = "t2.small"
consul_cluster_size = 1
consul_instance_type = "t2.small"
bootnode_cluster_size = 1
bootnode_instance_type = "t2.small"
quorum_node_instance_type = "t2.medium"
num_maker_nodes = 1
num_validator_nodes = 1
num_observer_nodes = 1
vote_threshold = 1
