# ---------------------------------------------------------------------------------------------------------------------
# REQUIRED PARAMETERS
# You must provide a value for each of these parameters.
# ---------------------------------------------------------------------------------------------------------------------
variable "aws_region" {
  description = "AWS region to launch servers."
}

variable "aws_key_pair_id" {
  description = "The ID of the AWS key pair to SSH into your instances"
}

variable "vote_threshold" {
  description = "The number of votes needed to confirm a block. This should be more than half of the number of validator nodes."
}

variable "vault_dns" {
  description = "The DNS name that vault will be accessible on."
}

variable "vault_cert_bucket_name" {
  description = "The name of the S3 bucket holding the vault TLS certificates"
}

variable "vault_cert_bucket_arn" {
  description = "The ARN of the S3 bucket holding the vault TLS certificates"
}

variable "consul_cluster_tag_key" {
  description = "The tag key of the consul cluster to use for vault cluster locking."
}

variable "consul_cluster_tag_value" {
  description = "The tag value of the consul cluster to use for vault cluster locking."
}

variable "vault_cert_s3_upload_id" {
  description = "Generated by quorum_vault after uploading certificates to S3. Used to work around lack of depends_on for modules."
}

variable "quorum_amis" {
  description = "Mapping from AWS region to AMI ID to use for quorum nodes in that region"
  type        = "map"
}

variable "bootnode_amis" {
  description = "Mapping from AWS region to AMI ID to use for bootnodes in that region"
  type        = "map"
}

# ---------------------------------------------------------------------------------------------------------------------
# OPTIONAL PARAMETERS
# These parameters have reasonable defaults.
# ---------------------------------------------------------------------------------------------------------------------
variable "network_id" {
  description = <<DESCRIPTION
Ethereum network ID, also used in naming some resources for uniqueness.
Must be unique amongst networks in the same AWS account and launched with this tool.
Ideally is globally unique amongst ethereum and quorum networks.
DESCRIPTION
  default = 64813
}

variable "vault_port" {
  description = "The port that vault will be accessible on."
  default     = 8200
}

variable "force_destroy_s3_buckets" {
  description = "Whether or not to force destroy s3 buckets. Set to true for an easily destroyed test environment. DO NOT set to true for a production environment."
  default     = false
}

variable "bootnode_instance_type" {
  description = "The EC2 instance type to use for bootnodes"
  default     = "t2.small"
}

variable "quorum_node_instance_type" {
  description = "The EC2 instance type to use for quorum nodes"
  default     = "t2.small"
}

variable "aws_azs" {
  description = "Mapping from AWS region to AZs to utilize in that region."
  type        = "map"
  default     = {
    # Virginia
    us-east-1      = ["us-east-1a", "us-east-1b", "us-east-1c"]
    # Ohio
    us-east-2      = ["us-east-2a", "us-east-2b", "us-east-2c"]
    # California
    us-west-1      = ["us-west-1a", "us-west-1b", "us-west-1c"]
    # Oregon
    us-west-2      = ["us-west-2a", "us-west-2b", "us-west-2c"]
    # Frankfurt
    eu-central-1   = ["eu-central-1a", "eu-central-1b", "eu-central-1c"]
    # Ireland
    eu-west-1      = ["eu-west-1a", "eu-west-1b", "eu-west-1c"]
    # London
    eu-west-2      = ["eu-west-2a", "eu-west-2b", "eu-west-2c"]
    # Mumbai
    ap-south-1     = ["ap-south-1a", "ap-south-1b"]
    # Tokyo
    ap-northeast-1 = ["ap-northeast-1a", "ap-northeast-1b", "ap-northeast-1c"]
    # Seoul
    ap-northeast-2 = ["ap-northeast-1a", "ap-northeast-1b"]
    # Singapore
    ap-southeast-1 = ["ap-southeast-1a", "ap-southeast-1b"]
    # Sydney
    ap-southeast-2 = ["ap-southeast-2a", "ap-southeast-2b", "ap-southeast-2c"]
    # Canada
    ca-central-1   = ["ca-central-1a", "ca-central-1b"]
    # South America
    sa-east-1      = ["sa-east-1a", "sa-east-1b", "sa-east-1c"]
  }
}

variable "bootnode_counts" {
  description = "A mapping from region to the number of bootnodes to launch in that region"
  type        = "map"
  default     = {
    # Virginia
    us-east-1      = 0
    # Ohio
    us-east-2      = 0
    # California
    us-west-1      = 0
    # Oregon
    us-west-2      = 0
    # Frankfurt
    eu-central-1   = 0
    # Ireland
    eu-west-1      = 0
    # London
    eu-west-2      = 0
    # Mumbai
    ap-south-1     = 0
    # Tokyo
    ap-northeast-1 = 0
    # Seoul
    ap-northeast-2 = 0
    # Singapore
    ap-southeast-1 = 0
    # Sydney
    ap-southeast-2 = 0
    # Canada
    ca-central-1   = 0
    # South America
    sa-east-1      = 0
  }
}

variable "maker_node_counts" {
  description = "A mapping from region to the number of maker nodes to launch in that region"
  type        = "map"
  default     = {
    # Virginia
    us-east-1      = 0
    # Ohio
    us-east-2      = 0
    # California
    us-west-1      = 0
    # Oregon
    us-west-2      = 0
    # Frankfurt
    eu-central-1   = 0
    # Ireland
    eu-west-1      = 0
    # London
    eu-west-2      = 0
    # Mumbai
    ap-south-1     = 0
    # Tokyo
    ap-northeast-1 = 0
    # Seoul
    ap-northeast-2 = 0
    # Singapore
    ap-southeast-1 = 0
    # Sydney
    ap-southeast-2 = 0
    # Canada
    ca-central-1   = 0
    # South America
    sa-east-1      = 0
  }
}

variable "validator_node_counts" {
  description = "A mapping from region to the number of validator nodes to launch in that region"
  type        = "map"
  default     = {
    # Virginia
    us-east-1      = 0
    # Ohio
    us-east-2      = 0
    # California
    us-west-1      = 0
    # Oregon
    us-west-2      = 0
    # Frankfurt
    eu-central-1   = 0
    # Ireland
    eu-west-1      = 0
    # London
    eu-west-2      = 0
    # Mumbai
    ap-south-1     = 0
    # Tokyo
    ap-northeast-1 = 0
    # Seoul
    ap-northeast-2 = 0
    # Singapore
    ap-southeast-1 = 0
    # Sydney
    ap-southeast-2 = 0
    # Canada
    ca-central-1   = 0
    # South America
    sa-east-1      = 0
  }
}

variable "observer_node_counts" {
  description = "A mapping from region to the number of observer nodes to launch in that region"
  type        = "map"
  default     = {
    # Virginia
    us-east-1      = 0
    # Ohio
    us-east-2      = 0
    # California
    us-west-1      = 0
    # Oregon
    us-west-2      = 0
    # Frankfurt
    eu-central-1   = 0
    # Ireland
    eu-west-1      = 0
    # London
    eu-west-2      = 0
    # Mumbai
    ap-south-1     = 0
    # Tokyo
    ap-northeast-1 = 0
    # Seoul
    ap-northeast-2 = 0
    # Singapore
    ap-southeast-1 = 0
    # Sydney
    ap-southeast-2 = 0
    # Canada
    ca-central-1   = 0
    # South America
    sa-east-1      = 0
  }
}
